backtestapp/urls.py
# backtestapp/urls.py

from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='inicio'),
    path('input/', views.input_page, name='input_page'),
    path('', views.home, name='inicio'),
    path('input2/', views.input_page2, name='input_page2'),
    
    
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from backtestapp import views
from backtestapp import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backtestapp.urls')),
]

backtestapp/models.py
from django.db import models
from django.core.validators import MinValueValidator, ValidationError

def no_negativo(value):
    if value < 0:
        raise ValidationError("El valor no puede ser negativo")

class StrategyParameters(models.Model):
    valorTK = models.FloatField(
        validators=[MinValueValidator(0), no_negativo]
    )
    startHour = models.TimeField()
    endHour = models.TimeField()
    fechaDesde = models.DateField()
    fechaHasta = models.DateField()
    tipoTK = models.CharField(max_length=1, choices=[('P', 'Puntos'), ('R', 'Ratio')])
    # Agrega campos para otras variables de la estrategia

class StrategyParameters2(models.Model):
    valorTK = models.FloatField(
        validators=[MinValueValidator(0), no_negativo]
    )
    startHour = models.TimeField()
    endHour = models.TimeField()
    fechaDesde = models.DateField()
    fechaHasta = models.DateField()
    stopLoss = models.FloatField(validators=[MinValueValidator(0), no_negativo])
    tipoTK = models.CharField(max_length=1, choices=[('P', 'Puntos'), ('R', 'Ratio')])
    # Agrega campos para otras variables de la estrategia

backtestapp/forms.py
from django import forms
from .models import StrategyParameters,StrategyParameters2

class StrategyParametersForm(forms.ModelForm):
    class Meta:
        model = StrategyParameters
        fields = ['valorTK', 'startHour', 'endHour', 'fechaDesde', 'fechaHasta', 'tipoTK']
        widgets = {
            'fechaDesde': forms.DateInput(attrs={'type': 'date'}),
            'fechaHasta': forms.DateInput(attrs={'type': 'date'}),
        }
      

class StrategyParameters2Form(forms.ModelForm):
    class Meta:
        model = StrategyParameters2
        fields = ['valorTK', 'startHour', 'endHour', 'fechaDesde', 'fechaHasta', 'tipoTK', 'stopLoss']
        widgets = {
                'fechaDesde': forms.DateInput(attrs={'type': 'date'}),
                'fechaHasta': forms.DateInput(attrs={'type': 'date'}),
        }

backtestapp/views.py
import logging
from django.shortcuts import render
from backtestapp.exeptions.NoTradesExeption import NoTradesException
from backtestapp.services.BackTestManager import BacktestManager
from backtestapp.services.Backtestmanager2 import BacktestManager2
from .strategy import ThreeCandlePatternStrategy
from .models import *
from .forms import StrategyParametersForm
from django.template import RequestContext
from .forms import StrategyParameters2Form
from .MauriStrategy import MauricioStrategy
from datetime import datetime
import backtrader as bt
import pandas as pd
import os


def input_page(request):
    if request.method == 'POST':
        form = StrategyParametersForm(request.POST)
        if form.is_valid():
            
            archivo_csv = 'dataKitInicial.csv'
            
            strategy = ThreeCandlePatternStrategy

            backtest_manager = BacktestManager(form, archivo_csv, strategy)
            
            results = backtest_manager.run_backtest()
            return render(request, 'results.html',results)
    else:
        form = StrategyParametersForm()
    return render(request, 'input_page.html', {'form': form})

def input_page2(request):
    
    if request.method == 'POST':
        form = StrategyParameters2Form(request.POST)
        if form.is_valid():
            try:
 
                strategy = MauricioStrategy

                backtest_manager = BacktestManager2(form, strategy)
                
                results = backtest_manager.run_backtest()
                return render(request, 'results.html',results)
            
            except NoTradesException as e:

                # Manejar la excepción y renderizar la plantilla 'exception.html'
                return render(request, 'exception.html', {'error_message': str(e)})
    else:
        form = StrategyParameters2Form()
    return render(request, 'input_page2.html', {'form': form})
   


def home(request):
      return render(request, 'home.html')

backtestapp/templates/exception.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f2f9ff;
        }

        .container {
            margin-top: 50px;
        }

        h1 {
            text-align: center;
            margin-top: 20px;
        }

        p {
            text-align: center;
             /* Cambia el color del texto de la excepción */
        }

        .btn {
            margin-top: 10px;
            position: absolute;
            top: 10px;
            left: 10px;
        }
        .card {
            background-color: white;
            border: 1px solid #ccc;
            border-radius: 10px;
            margin: 200px;
            padding: 20px;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
            transition: transform 0.2s;
            align-items: center;
            text-align: center;
        }


    </style>
    <title>Excepción en el backtest</title>
</head>
<body>
    <a href="" class="btn btn-primary">Volver a Configuración</a>
    <div class="card">
        <div class="container">
            <h1>¡Parece que no hay trades para la configuración actual!</h1>
            <p>{{ error_message }}</p>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

backtestapp/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>N&W TRADERS BACKTESTING</title>

    <style>
        /* Estilo de la barra de navegación */

        p {

            justify-content: center;
            align-items: center;
            text-align: center;
            font-size: 25px;
        }

        h1 {
            font-family: 'Purista SemiBold';
            text-align: center;
            /* Ahora centrado */
            margin-right: 50px;
        }

        .navbar {
            background-color: #0074b6;
            /* Azul profundo */
            color: white;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 15px 20px;
        }

        .logo {
            display: flex;
            align-items: center;
        }

        .logo img {
            max-width: 150px;
            /* Ajusta el tamaño del logotipo */
            margin-right: 10px;
            /* Reduzco el espacio para que quepa el título */
        }

        .navbar-title {
            flex: 1;
            /* Para que ocupe el espacio restante y se centre */
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        /* Estilo de los enlaces */
        .nav-links {
            display: flex;
        }

        .nav-links a {
            color: white;
            text-decoration: none;
            margin: 0 20px;
        }

        /* Contenido principal */
        .content {
            max-width: 1000px;
            /* Ampliado el ancho del contenido principal */
            margin: 0 auto;
            padding: 20px;
            background-color: #f4f4f4;
            border-radius: 10px;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
            /* Mayor sombra */
            margin-top: 50px;
        }

        h2 {
            text-align: center;
            font-size: 32px;
            color: #0074b6;
            /* Azul de enlace */
            margin-bottom: 20px;
        }

        .strategy-list {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
        }

        .strategy-card {
            background-color: white;
            border: 1px solid #ccc;
            border-radius: 10px;
            margin: 10px;
            padding: 20px;
            width: 300px;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
            transition: transform 0.2s;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .strategy-card:hover {
            transform: scale(1.05);
            box-shadow: 0 12px 20px rgba(0, 0, 0, 0.2);
            /* Mayor zoom y sombra al pasar el cursor */
        }

        .strategy-title {
            font-size: 24px;
            color: #0074b6;
            /* Azul de enlace */
            text-align: center;
        }

        .strategy-description {
            font-size: 24px;
            /* Aumento del tamaño del Tipo 2 */
            margin-top: 10px;
            text-align: center;
            /* Centrado del texto */
            text-decoration-color: #0074b6;
        }

        a.configure-button {
            text-align: center;
            margin-top: 20px;
            /* Espacio superior para el botón */
        }

        /* Estilos para el modo oscuro */
    </style>
</head>

<body>
    <!-- Barra de navegación -->
    <div class="navbar">
        <div class="logo">
            <img src="http://nwprofessionaltraders.com/wp-content/uploads/2022/06/NW-logo.svg" alt="Logo de la Empresa">
        </div>
        <div class="navbar-title">
            <h1>N&W PROFESSIONAL TRADERS</h1>
        </div>
    </div>

    <!-- Contenido principal -->
    <div class="content">
        <h2>Elige una estrategia</h2>
        <div class="strategy-list">
            <div class="strategy-card">
                <h3 class="strategy-title">Estrategia "Trampas"</h3>
                <p class="strategy-description">Tipo 2</p>
                <a href="input/" class="btn btn-primary configure-button">Configurar Estrategia</a>
            </div>

            <div class="strategy-card">
                <h3 class="strategy-title">Estrategia "L3 Banker Fund Flow Trend Oscillator"</h3>
                <p class="strategy-description"></p>
                <a href="input2/" class="btn btn-primary configure-button">Configurar Estrategia</a>
            </div>

        </div>
    </div>
</body>

</html>

backtestapp/templates/input_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="{% static 'javascript/input_page.js' %}"></script>
    <title>N&W TRADERS BACKTESTING</title>

</head>

<body>
    <a href="/" class="home-button">Volver al Home</a>

    <div id="container" class="container">
        <h1>Configuración De Estrategia</h1>
        <form method="post" class="form-group" id="backtesting-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="tipoTK">Tipo De Take Profit:</label>
                {{ form.tipoTK }}
            </div>
            <div class="form-group">
                <label for="valorTK">Valor De Take Profit:</label>
                {{ form.valorTK }}
            </div>
            <div class="form-group">
                <label for="startHour">Hora de Inicio: HH:MM</label>
                {{ form.startHour }}
            </div>
            <div class="form-group">
                <label for="endHour">Hora de Fin: HH:MM</label>
                {{ form.endHour }}
            </div>
            <div class="form-group">
                <label for="fechaDesde">Fecha Comienzo</label>
                {{ form.fechaDesde }}
            </div>
            <div class="form-group">
                <label for="fechaHasta">Fecha Final</label>
                {{ form.fechaHasta }}
            </div>
            <div class="form-group">
                <button type="submit" id="execute-button" class="btn btn-primary">Ejecutar BackTesting</button>
            </div>

        </form>
        
        <div class="overlay" id="processing-message" style="display: none;">
            <div class="loader"></div>
            <p class="processing-text" style="color: #fff;">Procesando BackTesting, por favor espera...</p>
        </div>

        <div id="error-message">{{ error_message }}</div>

    </div>
    <script>
        // Cambia el valor predeterminado según tus necesidades
        var fechaDesde = "2023-05-01";
        var fechaHasta = "2023-09-30";
        var startHour = "10:30";
        var endHour = "17:00";

        $(document).ready(function() {
            // Asigna el valor predeterminado al campo fechaDesde
            $("#id_fechaDesde").val(fechaDesde);
            $("#id_fechaHasta").val(fechaHasta);
            $("#id_startHour").val(startHour);
            $("#id_endHour").val(endHour);
        });
    </script>

</body>

</html>

backtestapp/templates/input_page2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>  <!-- Agrega jQuery -->
    <script src="{% static 'javascript/input_page2.js' %}"></script>
    
    <title>N&W TRADERS BACKTESTING</title>

</head>

<body>
    <a href="/" class="home-button">Volver al Home</a>

    <div id="container" class="container">
        <h1>Configuración De Estrategia</h1>
        <form method="post" class="form-group" id="backtesting-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="tipoTK">Tipo De Take Profit:</label>
                {{ form.tipoTK }}
            </div>
            <div class="form-group">
                <label for="valorTK">Valor De Take Profit:</label>
                {{ form.valorTK }}
            </div>
            <div class="form-group">
                <label for="stopLoss">Valor De Stop Loss:</label>
                {{ form.stopLoss }}
            </div>
            <div class="form-group">
                <label for="startHour">Hora de Inicio: HH:MM</label>
                {{ form.startHour }}
            </div>
            <div class="form-group">
                <label for="endHour">Hora de Fin: HH:MM</label>
                {{ form.endHour }}
            </div>
            <div class="form-group">
                <label for="fechaDesde">Fecha Comienzo</label>
                {{ form.fechaDesde }}
            </div>
            <div class="form-group">
                <label for="fechaHasta">Fecha Final</label>
                {{ form.fechaHasta }}
            </div>
            <div class="form-group">
                <button type="submit" id="execute-button" class="btn btn-primary">Ejecutar BackTesting</button>
            </div>

        </form>
        
        <div class="overlay" id="processing-message" style="display: none;">
            <div class="loader"></div>
            <p class="processing-text" style="color: #fff;">Procesando BackTesting, por favor espera...</p>
        </div>

        <div id="error-message">{{ error_message }}</div>

    </div>
    <script>
        // Cambia el valor predeterminado según tus necesidades
        var fechaDesde = "2023-01-04";
        var fechaHasta = "2023-12-14";
        var startHour = "11:00";
        var endHour = "18:00";

        $(document).ready(function() {
            // Asigna el valor predeterminado al campo fechaDesde
            $("#id_fechaDesde").val(fechaDesde);
            $("#id_fechaHasta").val(fechaHasta);
            $("#id_startHour").val(startHour);
            $("#id_endHour").val(endHour);
        });
    </script>

</body>

</html>

backtestapp/templates/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f2f9ff;
        }

        .container {
            margin-top: 50px;
        }

        table {
            background-color: #fff;
            border: 2px solid #007BFF;
            border-radius: 20px; /* Aumenta la curvatura */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin: 20px 0; /* Agrega espacio entre la tabla y otros elementos */
        }

        th, td {
            text-align: center;
            vertical-align: middle;
        }

        th {
            background-color: #007BFF;
            color: #fff;
        }
        .configure-button {
            position: absolute;
            top: 10px; /* Ajusta la distancia desde la parte superior */
            left: 10px; /* Ajusta la distancia desde la izquierda */
        }
        h1{
            text-align: center;
            margin-top: 20px;
            
        }
    </style>
    <title>Tabla de Backtesting</title>
</head>
<body>
  
    <div class="container">
        <div class="table-responsive">
          <a href="" class="btn btn-primary configure-button">Volver a Configuración</a>
            
            <table class="table table-bordered table-hover table-striped">
                <h1>Trades</h1>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Value</th>
                    </tr>
                    <tbody>
                       
                        <tr>
                            <td>Total:</td>
                            <td>{{totaltrades}}</td>
                            </tr>
                            <tr>
                            <td>Won streak:</td>
                            <td>{{rachaganadora}}</td>
                            </tr>
                            <tr>
                            <td>Lost streak:</td>
                            <td>{{rachaperdedora}}</td>
                            </tr>
                            <tr>
                            <td>Won:</td>
                            <td>{{totalganados}}</td>
                            </tr>
                            <tr>
                            <td>Lost:</td>
                            <td>{{totalperdidos}}</td>
                            </tr>
                            <tr>
                            <td>Longs:</td>
                            <td>{{longTotal}}</td>
                            </tr>
                            <tr>
                            <td>Shorts:</td>
                            <td>{{shortTotal}}</td>
                            </tr>
                            <tr>
                            <td>Won Longs:</td>
                            <td>{{longWins}}</td>
                            </tr>
                            <tr>
                            <td>Lost Longs:</td>
                            <td>{{longLost}}</td>
                            </tr>
                            <tr>
                            <td>Won Shorts:</td>
                            <td>{{shortWins}}</td>
                            </tr>
                            <tr>
                            <td>Lost Shorts:</td>
                            <td>{{shortLost}}</td>
                            </tr>
                    </tbody>
                    </thead>
            </table>
                    
            <table class="table table-bordered table-hover table-striped">
                <h1>PNL</h1>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Value</th>
                    </tr>
                    <tbody>
                        <td>Net:</td>
                        <td>{{pnl}}</td>
                        </tr>
                        <tr>
                        <td>Won PNL total:</td>
                        <td>{{pnlwins}}</td>
                        </tr>
                        <tr>
                        <td>Lost PNL total:</td>
                        <td>{{pnlLosts}}</td>
                        </tr>
                        <tr>
                        <td>Longs PNL total:</td>
                        <td>{{pnllong}}</td>
                        </tr>
                        <tr>
                        <td>Shorts PNL total:</td>
                        <td>{{pnlShort}}</td>
                        </tr>
                        <tr>
                        <td>Won longs PNL:</td>
                        <td>{{pnlLongWins}}</td>
                        </tr>
                        <tr>
                        <td>Lost longs PNL:</td>
                        <td>{{pnlLongLosts}}</td>
                        </tr>
                        <tr>
                        <td>Won shorts PNL:</td>
                        <td>{{pnlShortWins}}</td>
                        </tr>
                        <tr>
                        <td>Lost shorts PNL:</td>
                        <td>{{pnlShortLosts}}</td>
                        </tr>
                        
                    </tbody>
           
            </table>
            <table class="table table-bordered table-hover table-striped">
                <h1>DrawDown</h1>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Value</th>
                    </tr>
                    <tbody>
                         <td>DrawDown length:</td>
            <td>{{lendraw}}</td>
            </tr>
            <td>DrawDown %:</td>
            <td>{{drawdown}}</td>
            </tr>
            <td>DrawDown Money $:</td>
            <td>{{moneydown}}</td>
            </tr>
            <td>Max Drawdown length:</td>
            <td>{{lenMax}}</td>
            </tr>
            <td>Max DrawDown %:</td>
            <td>{{drawMax}}</td>
            </tr>
            <td>Max Drawdown Money $:</td>
            <td>{{moneyMax}}</td>
            </tr>
                  
                    </thead>
            </table>
            <table class="table table-bordered table-hover table-striped">
                <h1>Length (bars in the market)</h1>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Value</th>
                    </tr>
                    <tbody>
                        <tr>
                            <td>Total:</td>
                            <td>{{recorridoEnOperaciones}}</td>
                            </tr>
                            <tr>
                            <td>Average per Trades:</td>
                            <td>{{promedioVelasOperacion}}</td>
                            </tr>
                            <tr>
                            <td>Max per Trades:</td>
                            <td>{{maxvelasOperacion}}</td>
                            </tr>
                            <tr>
                            <td>Min per Trades:</td>
                            <td>{{minvelasOperacion}}</td>
                            </tr>
                    </tbody>
                    </thead>
            </table>
           
            <table class="table table-bordered table-hover table-striped">
                <h1>Length Target/Stop</h1>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Value</th>
                    </tr>
                    <tbody>
                        <tr>
                            <td>Total per Win Trades:</td>
                            <td>{{recorridoOperacionesGanadas}}</td>
                            </tr>
                            <tr>
                            <td>Average per Win Trades:</td>
                            <td>{{promedioVelasOperacionGanadas}}</td>
                            </tr>
                            <tr>
                            <td>Max per Win Trades:</td>
                            <td>{{maxvelasOperacionGanadas}}</td>
                            </tr>
                            <tr>
                            <td>Min per Win Trades:</td>
                            <td>{{minvelasOperacionGanadas}}</td>
                            </tr>
                            <tr>
                            <td>Total per Lost Trades:</td>
                            <td>{{recorridoOperacionesPerdidas}}</td>
                            </tr>
                            <tr>
                            <td>Average per Lost Trades:</td>
                            <td>{{promedioVelasOperacionPerdidas}}</td>
                            </tr>
                            <tr>
                            <td>Max per Lost Trades:</td>
                            <td>{{maxvelasOperacionPerdidas}}</td>
                            </tr>
                            <tr>
                            <td>Min per Lost Trades:</td>
                            <td>{{minvelasOperacionPerdidas}}</td>
                            </tr>
                    </tbody>
                    </thead>
            </table>
            <table class="table table-bordered table-hover table-striped">
                <h1>Length Longs</h1>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Value</th>
                    </tr>
                    <tbody>
                      
                        <tr>
                            <td>Total per Long Trades:</td>
                            <td>{{long_total}}</td>
                            </tr>
                            <tr>
                            <td>Average per Long Trades:</td>
                            <td>{{long_average}}</td>
                            </tr>
                            <tr>
                            <td>Max per Long Trades:</td>
                            <td>{{long_max}}</td>
                            </tr>
                            <tr>
                            <td>Min per Long Trades:</td>
                            <td>{{long_min}}</td>
                            </tr>
                    </tbody>
                    </thead>
            </table>
            
            <table class="table table-bordered table-hover table-striped">
                <h1>Length Shorts</h1>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Total per Short Trades:</td>
                        <td>{{short_total}}</td>
                        </tr>
                        <tr>
                        <td>Average per Short Tradest:</td>
                        <td>{{short_average}}</td>
                        </tr>
                        <tr>
                        <td>Max per Short Trades:</td>
                        <td>{{short_max}}</td>
                        </tr>
                        <tr>
                        <td>Min per Short Tradest:</td>
                        <td>{{short_min}}</td>
                        </tr>
                </tbody>
            </table>
            
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>